apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-ypzi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-ypzi
    app.kubernetes.io/part-of: test-app-hqxc
  name: docker-devfile-sample-hello-world-ypzi
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-ypzi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-ypzi
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/build-e2e-cqwr-tenant/test-app-hqxc/docker-devfile-sample-hello-world-ypzi@sha256:54ce0c346125890d50a4664c671a131d328a16d42bc24e78912a7e7c308e50d3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
