apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-ypzi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-ypzi
    app.kubernetes.io/part-of: test-app-hqxc
  name: docker-devfile-sample-hello-world-ypzi
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-ypzi
status:
  loadBalancer: {}
